management.endpoints.web.exposure.include=health,info,modulith

rallyon.security.keycloak.permit-all[0]=/actuator/health/**
rallyon.security.keycloak.permit-all[1]=/actuator/info
rallyon.security.keycloak.permit-all[2]=/swagger-ui/**
rallyon.security.keycloak.permit-all[3]=/v3/api-docs/**
rallyon.security.keycloak.permit-all[4]=/actuator/modulith
rallyon.security.keycloak.permit-all[5]=/actuator/modulith/**
